tesco:
  - username: foo
    password: bar
    phoneNumbers:
      - baz

puppeteer:
  options:
    headless: true
  closeOnError: true
  timeout: 60000

twilio:
  accountSid: AC479050186f2a17f5874a17cdd57f2f03
  authToken: bar
  from: '+441173253659'

sentry:
  enabled: false
  dsn: foo

schedule: '*/10 * * * *'

runOnStart: false

alwaysSendTexts: false
